### ISSUE TITLE
telnet version

### ISSUE THREAD

**Issue by dongalor** [skeeto/goblin-com#2]
```
telnetd: /tmp/gcom: No such file or directory
.
??#Connection closed by foreign host.
```

p.s. love your work )

**Comment by skeeto** [comment]
Oops, I thought I removed the telnet listing in the README. I took that
service down awhile ago. It's not something I want to host long-term
(extra server load, security concerns) and was primarily there to aid in
7DRL judging (only need a telnet client), but that was finished over a
year ago. Thanks for the heads up! If you're having trouble running it
locally, let me know.
